### ISSUE TITLE
News order is not right

### ISSUE THREAD

**Issue by SoonDead** [stepmania/stepmania-site#62]
On the news page the listed forum topics are not in the correct order.

You can see that the 5.0.7 announcement is on the top even over the 5.0.8 announcement.

They are ordered by the date of the last comment in each topic.

They should be ordered by the date when each topic is opened.

I have no idea how does silverstripe access data, but it seems to be some kind of [lazy-loading magic](http://api.silverstripe.org/3.1/class-DataList.html) .

Something like `<% loop Topics.Sort('Topic creation date DESC').Limit(15) %>` might work.

**Comment by shakesoda** [comment]
fixed (a while back, actually, but it's committed now)
