### ISSUE TITLE
Outdated links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ianklatzco** [stepmania/stepmania-site#65]
These return dead links: https://github.com/stepmania/stepmania-site/blob/master/CONTRIBUTING.md. Perhaps this file should be updated/deleted? Appears to be the default silverstripe file.

**Comment by shakesoda** [comment]
yeah, that file can go.

I haven't made any time in quite a while to work on this, the list of things that need work has grown quite a bit (silverstripe upgrade, switch email sending to use mailgun or something, new captcha, better moderation tools...)

**Comment by shakesoda** [comment]
deleted
