### ISSUE TITLE
New static website frontend in Github Pages

### ISSUE THREAD

**Issue by andrewerb** [stepmania/stepmania-site#70]
To mitigate some of the downtime of the current [stepmania.com](http://www.stepmania.com) site, perhaps we can create a simpler static-site solely for releases, download links, and pertinent details. We could host this on [Github Pages](https://pages.github.com/).

This page could largely mirror the current frontend, but allow us to decouple content served from the current PHP hosted server. The frontend could easily still serve the site as one unified experience, but with forums serving from a separate server/subdomain, etc.

We could keep _forums_ on the the current PHP server hosting, and likely reduce traffic to that aspect of the site–hopefully alleviating some of the current server load and thus serving both sides more reliably. Additionally, we could count on more reliable uptime for the bare essentials for which many users navigate to the site.

Blog content could either be left on the PHP-site, or moved to this static-site with one of the many static-site generators such as [Gatsby](https://www.gatsbyjs.org/) or [Jekyll](https://jekyllrb.com/), both of which play well with Github Pages.

**Comment by shakesoda** [comment]
the entire reason for the downtime is just that i need to reconfigure the machine.

i screwed up the boot services with one of the os updates, and just really need to fix that it needs manual intervention after every reboot. it's on my todo list.
